# Generated by Django 4.2 on 2023-04-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayt', '0002_basket_create_date_product_sub_ctg_sub_ctg_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
