# Generated by Django 4.2 on 2023-04-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayt', '0003_category_img_product_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=1024, unique=True)),
                ('email', models.CharField(max_length=128, unique=True)),
                ('is_expired', models.BooleanField(default=False)),
                ('tries', models.SmallIntegerField(default=0)),
                ('state', models.CharField(max_length=128)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
