# Generated by Django 4.2 on 2023-04-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayt', '0005_alter_comment_product_alter_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='email',
            field=models.CharField(max_length=128),
        ),
    ]
