# Generated by Django 4.1.6 on 2023-05-09 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sayt', '0008_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='img',
        ),
        migrations.RemoveField(
            model_name='product',
            name='img',
        ),
    ]
