# Generated by Django 4.1.6 on 2023-05-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayt', '0008_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=128)),
                ('signed_up', models.BooleanField(default=False, verbose_name='Royxatdan otganmi:')),
                ('agreement', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='delivery_types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_magazine', models.BooleanField()),
                ('from_deliver', models.BooleanField()),
                ('from_comp', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=128)),
                ('region', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='payment_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash', models.BooleanField()),
                ('card', models.BooleanField()),
                ('bank_doc', models.BooleanField()),
                ('kredit', models.BooleanField()),
                ('payment_comp', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='img',
        ),
        migrations.RemoveField(
            model_name='product',
            name='img',
        ),
    ]
