# Generated by Django 4.1.6 on 2023-04-12 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_alter_user_options_user_date_joined_user_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
